# Generated by Django 5.1.1 on 2025-01-02 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogs", "0002_alter_blogs_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogs",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
